### ISSUE TITLE
Current "get around" require statement breaks

### ISSUE THREAD

**Issue by dapplion** [jacobheun/timeout-abort-controller#9]
Running Lodestar on this branch https://github.com/ChainSafe/lodestar/pull/2328 breaks with

```
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/app/node_modules/timeout-abort-controller/index.js:12:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/app/node_modules/libp2p/src/dialer/index.js:9:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
/usr/app/node_modules/timeout-abort-controller/index.js:12
class TimeoutController extends AbortController {
                                ^
```

Seems that this detection does not cover some corner case

https://github.com/jacobheun/timeout-abort-controller/blob/653c45c3d7d0cc636e2518964e93178e6a43908c/index.js#L5-L8

**Comment by dapplion** [comment]
In a NodeJS environment `self` is defined and does not contain the AbortController property
```
{
  self: Object [global] {
    global: [Circular],
    clearInterval: [Function: clearInterval],
    clearTimeout: [Function: clearTimeout],
    setInterval: [Function: setInterval],
    setTimeout: [Function: setTimeout] {
      [Symbol(nodejs.util.promisify.custom)]: [Function]
    },
    queueMicrotask: [Function: queueMicrotask],
    clearImmediate: [Function: clearImmediate],
    setImmediate: [Function: setImmediate] {
      [Symbol(nodejs.util.promisify.custom)]: [Function]
    },
    self: [Circular]
  }
}
```

**Comment by wemeetagain** [comment]
The issue stems from the `threads` library attaching a global `self` object when its required.

Simple test case:
```js
require('threads');
require('timeout-abort-controller');
```
